--- # Default general configuration for the API.

app:
  env: development
  version: 1
  port: 8000
  lngs:
    - it
    - en
  defaultLng: it

crs:
  1: "+proj=longlat +datum=WGS84 +no_defs" # EPSG:4326 - WGS 84
  2: "+proj=utm +zone=32 +datum=WGS84 +units=m +no_defs" # EPSG:32632 - WGS 84 / UTM zone 32
  3: "+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs" # EPSG:2056 - CH1903+ / LV95
