--- # Configuration of the API endpoints.

/auth:

  - path: /register
    method: POST
    token_required: false

  - path: /login
    method: POST
    token_required: false

/users:

  - path: /:id
    method: GET
    token_required: true

  - path: /:id/change-email
    method: PATCH
    token_required: true

  - path: /:id/change-password
    method: PATCH
    token_required: true

  - path: /:id/change-info
    method: PATCH
    token_required: true

/rois:

  - path: ""
    method: GET
    token_required: false

/events:

  - path: ""
    method: GET
    token_required: false
    sort:
      - date

  - path: ""
    method: POST
    token_required: true

  - path: /:id
    method: GET
    token_required: false

  - path: /:id
    method: PUT
    token_required: true

  - path: /:id
    method: DELETE
    token_required: true

/alerts:

  - path: ""
    method: GET
    token_required: false
    sort:
      - createdAt
      - dateEnd

  - path: ""
    method: POST
    token_required: true

  - path: /:id
    method: GET
    token_required: false

  - path: /:id
    method: PUT
    token_required: true

  - path: /:id
    method: DELETE
    token_required: true

/observations:

  - path: ""
    method: GET
    token_required: false

  - path: ""
    method: POST
    token_required: false
    upload:
      dest: ./uploads/observations
      fields:
        - min: 0
          max: 3
          name: photos
        - min: 0
          max: 1
          name: signage

  - path: /:id
    method: GET
    token_required: false

  - path: /:id
    method: DELETE
    token_required: true

/misc:
  - path: /weather
    method: GET
    token_required: false

/docs:
  - path: ""
    method: GET
    token_required: false
